osx_image: xcode7
language: objective-c
xcode_sdk: iphonesimulator
xcode_workspace: WAAccountStoreDemo/WAAccountStoreDemo.xcworkspace
xcode_scheme: WAAccountStoreDemo
podfile: WAAccountStoreDemo/Podfile
